### PR TITLE
feat: updated workflow to automate github and pub.dev release

### PR DESCRIPTION
**Pull request by MrUnfunny**
Fix: https://github.com/casbin/dart-casbin/issues/45

@hsluoyz @KNawm please review. We will need to add a secret named PUB_CREDENTIALS according to [this instruction](https://github.com/sakebook/actions-flutter-pub-publisher#credential).

### CODE REVIEW

**Comment by hsluoyz** [comment]
@MrUnfunny is that the Gmail password? Added.

image

**Comment by MrUnfunny** [comment]
@hsluoyz no, when you manually publish the package, it creates a credentials.json file in .pub-cache. That file data should be added here.

**Comment by hsluoyz** [comment]
@MrUnfunny Unfortunately I have migrated to a new computer and the `.pub-cache` folder is lost. How to do it?

**Comment by hsluoyz** [comment]
@MrUnfunny can you fix this first? When I run `dart pub publish --dry-run`, I saw:

image

**Comment by MrUnfunny** [comment]
@hsluoyz should I send a new PR for this or change in this PR only?

**Comment by hsluoyz** [comment]
@MrUnfunny new PR plz

**Comment by hsluoyz** [comment]
@MrUnfunny v0.1.0 done: https://pub.dev/packages/casbin

**Comment by hsluoyz** [comment]
Done with secret:

image

**Comment by MrUnfunny** [comment]
@hsluoyz the workflow seems to work fine. The publish step failed because we already had v0.1.0 on pub.dev. Apart from this, it seems fine.

**Comment by hsluoyz** [comment]
@MrUnfunny so I think we doesn't need to do anything for now, right? It will auto go well for next release?

**Comment by MrUnfunny** [comment]
yes. But still, to be sure, I'll soon implement IPMatchFunc or getImplicitRoles. Then we can test the publish step as well.

**Comment by hsluoyz** [comment]
Great!

**Pull request merged**
