### PR TITLE
refactor: refactored the function_name

### PR DESCRIPTION
**Pull request by Rishabhmodii**
Changed all functions to follow Golang Casbin's naming convention.

Fix: https://github.com/casbin/dart-casbin/issues/51

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Rishabhmodii plz fix:

image

**Comment by hsluoyz** [comment]
@MrUnfunny @xiaobeiswift plz review

**Comment by MrUnfunny** [comment]
@Rishabhmodii please refactor other modules as well.

**Comment by Rishabhmodii** [comment]
> @Rishabhmodii please refactor other modules as well.

 I am currently doing changes in this https://github.com/casbin/dart-casbin/pull/53

**Comment by MrUnfunny** [comment]
> I am currently doing changes in this #53

Hi @Rishabhmodii , I think we should keep all refactoring code in the same PR. You can create different commits for different modules here only.

**Comment by MrUnfunny** [comment]
@hsluoyz LGTM

**Pull request merged**
