### PR TITLE
feat: Implement config interface

### PR DESCRIPTION
**Pull request by ctrysbita**
This pull request implements:

- Milestone 1
  - config interface

No tests changed due to this pr.

### CODE REVIEW

**Comment by MrUnfunny** [comment]
Hi @ctrysbita 
This part was inspired from [jcasbin](https://github.com/casbin/jcasbin) and I think because ConfigInterface is used only by Config, it was skipped in both jcasbin and dart-casbin.

**Comment by ctrysbita** [comment]
@ctrysbita The interface is designed for package users to make custom config implementation. Not for us XD

**Comment by hsluoyz** [comment]
@KNawm plz review.

**Comment by MrUnfunny** [comment]
@ctrysbita thanks for clarifying. I was not aware of this. 
@hsluoyz jcasbin does not seem to have a configInterface, was it intentional for some reason, or was it missed.

**Pull request merged**
